name: Townsq Github Actions

on:
    push:
        branches: ["*"]

jobs:
  cypress-run:
    steps:
      uses: cypress-io/github-action@v4.2.0

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm ci

            - run: npm run build
            - run: npm run deploy